/*
 * Copyright MapStruct Authors.
 *
 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package org.mapstruct.ap.internal.util;

import java.util.HashSet;
import java.util.Set;

import org.mapstruct.ap.internal.langmodel.descriptor.LangTypeKind;
import org.mapstruct.ap.internal.langmodel.descriptor.TypeDescriptor;
import org.mapstruct.ap.internal.util.AnnotationProcessorContextView;
import org.mapstruct.ap.spi.TypeHierarchyErroneousException;

/**
 * Keeps contextual data in the scope of one annotation processing round.
 *
 * @author Gunnar Morling
 */
public class RoundContext {

    private final AnnotationProcessorContextView annotationProcessorContext;
    private final Set<String> clearedTypeIds;

    public RoundContext(AnnotationProcessorContextView annotationProcessorContext) {
        this.annotationProcessorContext = annotationProcessorContext;
        this.clearedTypeIds = new HashSet<>();
    }

    public AnnotationProcessorContextView getAnnotationProcessorContext() {
        return annotationProcessorContext;
    }

    /**
     * Marks the given type as being ready for further processing.
     *
     * @param descriptor the type that is ready for further processing by MapStruct
     */
    public void addTypeReadyForProcessing(TypeDescriptor descriptor) {
        if ( descriptor == null ) {
            return;
        }
        String typeId = descriptor.id();
        if ( typeId != null ) {
            clearedTypeIds.add( typeId );
        }
    }

    /**
     * Whether the given type has been found to be ready for further processing or not. This is the case if the type's
     * hierarchy is complete (no super-types need to be generated by other processors) and no processors have signaled
     * the intention to amend the given type.
     *
     * @param descriptor the type to be checked for its readiness
     * @return true when the type is ready to be processed by MapStruct
     */
    public boolean isReadyForProcessing(TypeDescriptor descriptor) {
        if ( descriptor == null ) {
            return false;
        }
        String typeId = descriptor.id();
        return typeId != null && clearedTypeIds.contains( typeId );
    }

    public boolean canBeProcessed(TypeDescriptor descriptor) {
        if ( descriptor != null && descriptor.kind() == LangTypeKind.ERROR ) {
            return false;
        }
        if ( descriptor == null || descriptor.kind() != LangTypeKind.DECLARED ) {
            return true;
        }

        if ( isReadyForProcessing( descriptor ) ) {
            return true;
        }

        if ( annotationProcessorContext.isTypeComplete( descriptor ) ) {
            addTypeReadyForProcessing( descriptor );
            return true;
        }

        return false;
    }

    public TypeHierarchyErroneousException typeHierarchyErroneousException(TypeDescriptor descriptor) {
        return annotationProcessorContext.typeHierarchyErroneousException( descriptor );
    }
}
